name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python -V

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: List files in directory
      - run: ls -la /home/runner/work/aplicacao-web-docker/aplicacao-web-docker/
      - uses: actions/checkout@v3
      - run: python teste.py

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
